### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by blogcraft** [smallstack/migrate-angular-flex-to-tailwind#1]
There where a lot of attributes it does not convert, some examples:
`fxFlexFill`
`fxFlex.lt-md="0 0 calc(50% - 10px)"`
`fxLayout.sm="row wrap"`

Somehow it translated this:
`fxLayout.sm="row wrap" fxLayout.xs="column" fxFlex="50%"`
Into this:
`fxLayout.sm="row wrap" fxLayout.xs="column" class="basis-NaN/1"`

and this:
`class="flex flex-row flex-wrap space-x-3 justify-between items-center basis-NaN/1"`
into this:
`fxLayout="row wrap" fxLayoutGap="10px" fxFlex="50%" fxLayoutAlign="space-between center"`

**Comment by blogcraft** [comment]
https://github.com/angular/flex-layout/issues/1426#issuecomment-1552268228

**Comment by maxfriedmann** [comment]
@blogcraft Yes, support for fxFlex in percentage is still missing, I added an exception for `*` here: https://github.com/smallstack/migrate-angular-flex-to-tailwind/blob/main/bin/index.js#LL83C9-L83C15, so you could extend the code there as well.

We never used percentages, rather used `50` instead of `50%`. 

Can you debug why line https://github.com/smallstack/migrate-angular-flex-to-tailwind/blob/main/bin/index.js#LL100C22-L100C42 does not work? `+fxFlex` should result in `50` in your case and therefore be converted to the correct fraction...

**Comment by maxfriedmann** [comment]
Fixed in v1.0.2
